# Generated by Django 4.0.6 on 2022-07-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativeworld', '0002_alter_contact_options_alter_contactadmin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactadmin',
            name='contact',
            field=models.CharField(max_length=15, verbose_name='Contact'),
        ),
    ]
