# Generated by Django 4.0.6 on 2022-07-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creativeworld', '0004_subcription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcription',
            new_name='Subscription',
        ),
    ]
