# Generated by Django 4.0.6 on 2022-07-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativeworld', '0007_rename_email_subscription_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name'),
        ),
    ]
